import Foundation
import MapKit

let root = FileManager.default.temporaryDirectory.appendingPathComponent("AtoZDetailsChecks-" + UUID().uuidString)
defer { try? FileManager.default.removeItem(at: root) }
let store = ALUNoteDetailsStore(root: root)
assert(store.ensure("Old note").created == nil, "Legacy creation date must not be invented")
store.noteSaved("Old note", text: "Existing body")
assert(store.ensure("Old note").edited == nil)
store.noteCreated("Target")
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels")
var changedNotifications = 0
let observer = NotificationCenter.default.addObserver(forName: .init("ALULibraryChanged"), object: nil, queue: nil) { _ in changedNotifications += 1 }
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels")
assert(changedNotifications == 0, "Unchanged reads must not restart place search")
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels\nCoffee")
assert(changedNotifications == 1, "Saving changed content must refresh recommendations")
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels")
NotificationCenter.default.removeObserver(observer)
let original = store.ensure("Target")
assert(original.created != nil && original.edited != nil)
let fixture = root.appendingPathComponent("voice.m4a")
try Data("fictional attachment fixture".utf8).write(to: fixture)
let attachment = try store.importFile(fixture, title: "Target", kind: "audio")
store.update("Target") { $0.tags = ["Errands"]; $0.placeQuery = "Target" }
store.renameNote("Target", to: "Target shopping")
let renamed = store.ensure("Target shopping")
assert(renamed.id == original.id && renamed.created == original.created)
assert(renamed.attachments == [attachment] && renamed.tags == ["Errands"] && renamed.placeQuery == "Target")
let attachmentBytes = try Data(contentsOf: store.fileURL("Target shopping", attachment.file))
assert(attachmentBytes == Data("fictional attachment fixture".utf8))
let reopened = ALUNoteDetailsStore(root: root)
assert(reopened.ensure("Target shopping").id == original.id)
assert(reopened.ensure("Target shopping").attachments == [attachment])
let inferred = NotePlaceIntent.infer(title: "Target", text: "Milk\nBatteries\nPaper towels", details: NoteDetails())
assert(inferred == NotePlaceIntent(query: "Target", automatic: true))
assert(NotePlaceIntent.infer(title: "Target", text: "Apples\nShirts", details: NoteDetails()) != nil)
assert(inferred!.matchesPlaceName("Target") && inferred!.matchesPlaceName("Target Grocery"))
assert(!inferred!.matchesPlaceName("Target Field") && !inferred!.matchesPlaceName("Target Practice"))
assert(NotePlaceIntent.infer(title: "Target Practice", text: "Buy paper targets", details: NoteDetails()) == nil)
assert(NotePlaceIntent.infer(title: "Target", text: "Quarterly sales target", details: NoteDetails()) == nil)
assert(NotePlaceIntent.infer(title: "Target", text: "- [x] Milk\n✓ Batteries", details: NoteDetails()) == nil)
let costco = NotePlaceIntent.infer(title: "Costco", text: "Milk\nCoffee", details: NoteDetails())!
assert(costco.matchesPlaceName("Costco Wholesale") && costco.matchesPlaceName("Costco Business Center"))
assert(!costco.matchesPlaceName("Costco Gas Station") && !costco.matchesPlaceName("Costco Tire Center"))
assert(NotePlaceIntent.infer(title: "Trader Joe’s shopping list", text: "Bread\nEggs", details: NoteDetails())!.matchesPlaceName("Trader Joe's"))
assert(NotePlaceIntent.infer(title: "Starbucks", text: "Pick up coffee", details: NoteDetails())!.matchesPlaceName("Starbucks Coffee Company"))
assert(NotePlaceIntent.infer(title: "Philz Coffee", text: "Buy coffee beans", details: NoteDetails())!.matchesPlaceName("Philz Coffee"), "Businesses outside a fixed chain list must work")
assert(NotePlaceIntent.infer(title: "Shopping at Village music shop", text: "Guitar strings", details: NoteDetails()) != nil)
assert(NotePlaceIntent.infer(title: "Costco", text: "* [X] Milk\n• [x] Coffee", details: NoteDetails()) == nil)
assert(NotePlaceIntent.infer(title: "https://private.example", text: "Buy milk", details: NoteDetails()) == nil)
let nearby = CLLocation(latitude: 37.323, longitude: -122.0322)
func place(_ name: String, _ category: MKPointOfInterestCategory, _ coordinate: CLLocationCoordinate2D) -> MKMapItem {
    let item = MKMapItem(location: CLLocation(latitude: coordinate.latitude, longitude: coordinate.longitude), address: nil)
    item.name = name; item.pointOfInterestCategory = category
    return item
}
let library = NotePlaceIntent.infer(title: "Library", text: "Return books", details: NoteDetails())!
assert(library.matches(place("Cupertino Library", .library, nearby.coordinate), near: nearby))
assert(!library.matches(place("Library Cafe", .cafe, nearby.coordinate), near: nearby))
assert(!costco.matches(place("Costco Wholesale", .foodMarket, CLLocationCoordinate2D(latitude: 34.1, longitude: -118.1)), near: nearby), "Far-away branches must not be monitored")
let grocery = NotePlaceIntent.infer(title: "Grocery store", text: "Bread\nEggs", details: NoteDetails())!
assert(grocery.matches(place("Safeway", .foodMarket, nearby.coordinate), near: nearby))
assert(!grocery.matches(place("Grocery Cafe", .restaurant, nearby.coordinate), near: nearby))
assert(NotePlaceIntent.searchRequest(query: library.query, near: nearby).pointOfInterestFilter!.includes(.library))
assert(!NotePlaceIntent.searchRequest(query: library.query, near: nearby).pointOfInterestFilter!.includes(.cafe))
var optedOut = NoteDetails(); optedOut.nearbyDisabled = true
assert(NotePlaceIntent.infer(title: "Target", text: "Milk", details: optedOut) == nil)
var custom = NoteDetails(); custom.placeQuery = "Village music shop"
assert(NotePlaceIntent.infer(title: "Guitar strings", text: "", details: custom)?.query == custom.placeQuery)
let unchangedDate = store.ensure("Target shopping").edited
store.noteSaved("Target shopping", text: "Milk\nBatteries\nPaper towels")
assert(store.ensure("Target shopping").edited == unchangedDate, "Opening an unchanged note must not change its edit date")
let drawn = try store.importFile(fixture, title: "Target shopping", kind: "drawing", drawing: Data("editable strokes".utf8))
let drawingBytes = try Data(contentsOf: store.fileURL("Target shopping", drawn.drawingFile!))
assert(drawingBytes == Data("editable strokes".utf8))
let replacement = try store.importFile(fixture, title: "Target shopping", kind: "drawing", drawing: Data("updated strokes".utf8), replacing: drawn.id)
assert(!store.ensure("Target shopping").attachments.contains(where: { $0.id == drawn.id }))
assert(store.ensure("Target shopping").attachments.contains(replacement))
// A failing manifest write must leave the previous attachment and note identity visible.
try FileManager.default.removeItem(at: root.appendingPathComponent("index.json"))
try FileManager.default.createDirectory(at: root.appendingPathComponent("index.json"), withIntermediateDirectories: false)
let beforeFailure = store.ensure("Target shopping")
assert(!store.update("Target shopping") { $0.tags = ["Must not persist"] })
assert(store.ensure("Target shopping").tags == beforeFailure.tags)
assert(!store.renameNote("Target shopping", to: "Failed rename"))
assert(store.records["Failed rename"] == nil && store.ensure("Target shopping").id == original.id)
let corrupted = root.appendingPathComponent("corrupted", isDirectory: true)
try FileManager.default.createDirectory(at: corrupted, withIntermediateDirectories: true)
let invalid = corrupted.appendingPathComponent("index.json")
try Data("invalid original bytes".utf8).write(to: invalid)
let broken = ALUNoteDetailsStore(root: corrupted); _ = broken.ensure("Do not overwrite")
assert(broken.errorMessage != nil)
let preservedBytes = try String(contentsOf: invalid, encoding: .utf8)
assert(preservedBytes == "invalid original bytes")
print("PASS: legacy dates, metadata, attachments, rename, cold reload, corruption preservation, store intent positives/negatives and opt-out")
