import Foundation

let root = FileManager.default.temporaryDirectory.appendingPathComponent("AtoZDetailsChecks-" + UUID().uuidString)
defer { try? FileManager.default.removeItem(at: root) }
let store = ALUNoteDetailsStore(root: root)
assert(store.ensure("Old note").created == nil, "Legacy creation date must not be invented")
store.noteSaved("Old note", text: "Existing body")
assert(store.ensure("Old note").edited == nil)
store.noteCreated("Target")
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels")
var changedNotifications = 0
let observer = NotificationCenter.default.addObserver(forName: .init("ALULibraryChanged"), object: nil, queue: nil) { _ in changedNotifications += 1 }
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels")
assert(changedNotifications == 0, "Unchanged reads must not restart place search")
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels\nCoffee")
assert(changedNotifications == 1, "Saving changed content must refresh recommendations")
store.noteSaved("Target", text: "Milk\nBatteries\nPaper towels")
NotificationCenter.default.removeObserver(observer)
let original = store.ensure("Target")
assert(original.created != nil && original.edited != nil)
let fixture = root.appendingPathComponent("voice.m4a")
try Data("fictional attachment fixture".utf8).write(to: fixture)
let attachment = try store.importFile(fixture, title: "Target", kind: "audio")
store.update("Target") { $0.tags = ["Errands"]; $0.placeQuery = "Target" }
store.renameNote("Target", to: "Target shopping")
let renamed = store.ensure("Target shopping")
assert(renamed.id == original.id && renamed.created == original.created)
assert(renamed.attachments == [attachment] && renamed.tags == ["Errands"] && renamed.placeQuery == "Target")
let attachmentBytes = try Data(contentsOf: store.fileURL("Target shopping", attachment.file))
assert(attachmentBytes == Data("fictional attachment fixture".utf8))
let reopened = ALUNoteDetailsStore(root: root)
assert(reopened.ensure("Target shopping").id == original.id)
assert(reopened.ensure("Target shopping").attachments == [attachment])
let inferred = NotePlaceIntent.infer(title: "Target", text: "Milk\nBatteries\nPaper towels", details: NoteDetails())
assert(inferred == NotePlaceIntent(query: "Target", automatic: true))
assert(NotePlaceIntent.infer(title: "Target", text: "Apples\nShirts", details: NoteDetails()) != nil)
assert(inferred!.matchesPlaceName("Target") && inferred!.matchesPlaceName("Target Grocery"))
assert(!inferred!.matchesPlaceName("Target Field") && !inferred!.matchesPlaceName("Target Practice"))
assert(NotePlaceIntent.infer(title: "Target Practice", text: "Buy paper targets", details: NoteDetails()) == nil)
assert(NotePlaceIntent.infer(title: "Target", text: "Quarterly sales target", details: NoteDetails()) == nil)
assert(NotePlaceIntent.infer(title: "Target", text: "- [x] Milk\n✓ Batteries", details: NoteDetails()) == nil)
var optedOut = NoteDetails(); optedOut.nearbyDisabled = true
assert(NotePlaceIntent.infer(title: "Target", text: "Milk", details: optedOut) == nil)
var custom = NoteDetails(); custom.placeQuery = "Village music shop"
assert(NotePlaceIntent.infer(title: "Guitar strings", text: "", details: custom)?.query == custom.placeQuery)
let unchangedDate = store.ensure("Target shopping").edited
store.noteSaved("Target shopping", text: "Milk\nBatteries\nPaper towels")
assert(store.ensure("Target shopping").edited == unchangedDate, "Opening an unchanged note must not change its edit date")
let drawn = try store.importFile(fixture, title: "Target shopping", kind: "drawing", drawing: Data("editable strokes".utf8))
let drawingBytes = try Data(contentsOf: store.fileURL("Target shopping", drawn.drawingFile!))
assert(drawingBytes == Data("editable strokes".utf8))
let replacement = try store.importFile(fixture, title: "Target shopping", kind: "drawing", drawing: Data("updated strokes".utf8), replacing: drawn.id)
assert(!store.ensure("Target shopping").attachments.contains(where: { $0.id == drawn.id }))
assert(store.ensure("Target shopping").attachments.contains(replacement))
// A failing manifest write must leave the previous attachment and note identity visible.
try FileManager.default.removeItem(at: root.appendingPathComponent("index.json"))
try FileManager.default.createDirectory(at: root.appendingPathComponent("index.json"), withIntermediateDirectories: false)
let beforeFailure = store.ensure("Target shopping")
assert(!store.update("Target shopping") { $0.tags = ["Must not persist"] })
assert(store.ensure("Target shopping").tags == beforeFailure.tags)
assert(!store.renameNote("Target shopping", to: "Failed rename"))
assert(store.records["Failed rename"] == nil && store.ensure("Target shopping").id == original.id)
let corrupted = root.appendingPathComponent("corrupted", isDirectory: true)
try FileManager.default.createDirectory(at: corrupted, withIntermediateDirectories: true)
let invalid = corrupted.appendingPathComponent("index.json")
try Data("invalid original bytes".utf8).write(to: invalid)
let broken = ALUNoteDetailsStore(root: corrupted); _ = broken.ensure("Do not overwrite")
assert(broken.errorMessage != nil)
let preservedBytes = try String(contentsOf: invalid, encoding: .utf8)
assert(preservedBytes == "invalid original bytes")
print("PASS: legacy dates, metadata, attachments, rename, cold reload, corruption preservation, store intent positives/negatives and opt-out")
